name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Web Platform Files
        run: |
          flutter config --enable-web
          flutter create --platforms web .

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href /geo-land-ts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
